// Frontend/src/pages/ListadoVotos.tsx
import { useEffect, useState } from 'react';
import api from '../api/client';

// Formatea una fecha "YYYY-MM-DD..." a DD/MM/YYYY sin pasar por Date(),
// para evitar que la conversion de zona horaria corra el dia (dob no tiene hora real).
function formatearFechaSolo(fechaIso: string): string {
  const [anio, mes, dia] = fechaIso.slice(0, 10).split('-');
  return `${dia}/${mes}/${anio}`;
}

interface VotoResumen {
  id: number;
  voter: { id: number; nombre: string; apellido: string };
  candidate: { id: number; nombre: string; apellido: string };
  voted_at: string;
}

interface VotoDetalle {
  id: number;
  voted_at: string;
  voter: {
    id: number;
    documento: string;
    tipo: string;
    nombre: string;
    apellido: string;
    dob: string;
    direccion: string;
    telefono: string;
    sexo: string;
  };
  candidate: { id: number; nombre: string; apellido: string };
}

interface ListadoResponse {
  va_ganando: { id: number; nombre: string; apellido: string } | null;
  empate: boolean;
  votos: {
    data: VotoResumen[];
    current_page: number;
    last_page: number;
  };
}

function ListadoVotos() {
  const [pagina, setPagina] = useState(1);
  const [datos, setDatos] = useState<ListadoResponse | null>(null);
  const [detalle, setDetalle] = useState<VotoDetalle | null>(null);
  const [cargando, setCargando] = useState(true);

  useEffect(() => {
  let esPrimeraCarga = true;

  const cargarDatos = () => {
    api.get<ListadoResponse>(`/votos?page=${pagina}`).then((res) => {
      setDatos(res.data);
      if (esPrimeraCarga) {
        setCargando(false);
        esPrimeraCarga = false;
      }
    });
  };

  cargarDatos();
  const intervalo = setInterval(cargarDatos, 1000); // Actualiza cada 1 segundo
  return () => clearInterval(intervalo);
}, [pagina]);

  const verDetalle = (id: number) => {
    api.get<VotoDetalle>(`/votos/${id}`).then((res) => setDetalle(res.data));
  };

  useEffect(() => {
    if (!detalle) return;
    const cerrarConEscape = (e: KeyboardEvent) => {
      if (e.key === 'Escape') setDetalle(null);
    };
    window.addEventListener('keydown', cerrarConEscape);
    return () => window.removeEventListener('keydown', cerrarConEscape);
  }, [detalle]);

  if (cargando || !datos) {
    return (
      <div>
        <h2>Listado de votos</h2>
        <div className="skeleton skeleton-line" style={{ width: '40%' }} />
        {[1, 2, 3, 4, 5].map((i) => (
          <div key={i} className="skeleton skeleton-row" />
        ))}
      </div>
    );
  }

  return (
    <div>
      <h2>Listado de votos</h2>

      {datos.empate && <p>Empate en el primer puesto</p>}
      {!datos.empate && datos.va_ganando && (
        <p>
          Va ganando: {datos.va_ganando.nombre} {datos.va_ganando.apellido}
        </p>
      )}

      <table>
        <thead>
          <tr>
            <th>Votante</th>
            <th>Candidato</th>
            <th>Fecha</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          {datos.votos.data.map((v, i) => (
            <tr key={v.id} style={{ animationDelay: `${Math.min(i, 8) * 40}ms` }}>
              <td>{v.voter.nombre} {v.voter.apellido}</td>
              <td>{v.candidate.nombre} {v.candidate.apellido}</td>
              <td>{new Date(v.voted_at).toLocaleString()}</td>
              <td>
                <button onClick={() => verDetalle(v.id)}>Ver detalle</button>
              </td>
            </tr>
          ))}
        </tbody>
      </table>

      <div>
        <button disabled={pagina <= 1} onClick={() => setPagina((p) => p - 1)}>
          Anterior
        </button>
        <span> Pagina {datos.votos.current_page} de {datos.votos.last_page} </span>
        <button
          disabled={pagina >= datos.votos.last_page}
          onClick={() => setPagina((p) => p + 1)}
        >
          Siguiente
        </button>
      </div>

      {detalle && (
        <div className="modal-overlay" onClick={() => setDetalle(null)}>
          <div className="modal-content" onClick={(e) => e.stopPropagation()}>
            <div className="modal-header">
              <h3>Detalle del voto</h3>
              <button className="modal-close" onClick={() => setDetalle(null)} aria-label="Cerrar">
                &times;
              </button>
            </div>

            <div className="modal-body">
              <div className="detalle-fila">
                <span>Documento</span>
                <strong>{detalle.voter.documento}</strong>
              </div>
              <div className="detalle-fila">
                <span>Tipo</span>
                <strong>{detalle.voter.tipo}</strong>
              </div>
              <div className="detalle-fila">
                <span>Nombre</span>
                <strong>{detalle.voter.nombre} {detalle.voter.apellido}</strong>
              </div>
              <div className="detalle-fila">
                <span>Fecha de nacimiento</span>
                <strong>{formatearFechaSolo(detalle.voter.dob)}</strong>
              </div>
              <div className="detalle-fila">
                <span>Direccion</span>
                <strong>{detalle.voter.direccion}</strong>
              </div>
              <div className="detalle-fila">
                <span>Telefono</span>
                <strong>{detalle.voter.telefono}</strong>
              </div>
              <div className="detalle-fila">
                <span>Sexo</span>
                <strong>{detalle.voter.sexo}</strong>
              </div>
              <div className="detalle-fila">
                <span>Voto a</span>
                <strong>{detalle.candidate.nombre} {detalle.candidate.apellido}</strong>
              </div>
              <div className="detalle-fila">
                <span>Fecha del voto</span>
                <strong>{new Date(detalle.voted_at).toLocaleString()}</strong>
              </div>
            </div>

            <button onClick={() => setDetalle(null)}>Cerrar</button>
          </div>
        </div>
      )}
    </div>
  );
}

export default ListadoVotos;

// frontend-angular/src/app/pages/admin/listado-votos/listado-votos.component.ts
import { Component, OnInit, OnDestroy, HostListener, inject, signal } from '@angular/core';
import { Subscription, timer, switchMap } from 'rxjs';
import { VotosService } from '../../../services/votos.service';
import { ListadoVotosResponse, VotoDetalle } from '../../../models/voto.model';
import { DatePipe } from '@angular/common';

function formatearFechaSolo(fechaIso: string): string {
  const [anio, mes, dia] = fechaIso.slice(0, 10).split('-');
  return `${dia}/${mes}/${anio}`;
}

@Component({
  selector: 'app-listado-votos',
  standalone: true,
  imports: [DatePipe],
  templateUrl: './listado-votos.component.html',
  styleUrl: './listado-votos.component.css',
})
export class ListadoVotosComponent implements OnInit, OnDestroy {
  private votosService = inject(VotosService);
  private sub?: Subscription;

  pagina = signal(1);
  datos = signal<ListadoVotosResponse | null>(null);
  detalle = signal<VotoDetalle | null>(null);
  cargando = signal(true);

  ngOnInit(): void {
    this.reiniciarPolling();
  }

  ngOnDestroy(): void {
    this.sub?.unsubscribe();
  }

  private reiniciarPolling(): void {
    this.sub?.unsubscribe();
    this.sub = timer(0, 1000)
      .pipe(switchMap(() => this.votosService.getVotos(this.pagina())))
      .subscribe((datos) => {
        this.datos.set(datos);
        this.cargando.set(false);
      });
  }

  irAPagina(delta: number): void {
    this.pagina.update((p) => p + delta);
    this.cargando.set(true);
    this.reiniciarPolling();
  }

  verDetalle(id: number): void {
    this.votosService.getDetalle(id).subscribe((detalle) => this.detalle.set(detalle));
  }

  cerrarDetalle(): void {
    this.detalle.set(null);
  }

  formatearFecha(fechaIso: string): string {
    return formatearFechaSolo(fechaIso);
  }

  @HostListener('window:keydown.escape')
  onEscape(): void {
    if (this.detalle()) this.cerrarDetalle();
  }
}
<div>
  <h2>Listado de votos</h2>

  @if (cargando() || !datos()) {
    <div class="skeleton skeleton-line" style="width: 40%"></div>
    @for (i of [1, 2, 3, 4, 5]; track i) {
      <div class="skeleton skeleton-row"></div>
    }
  } @else {
    @if (datos()!.empate) {
      <p>Empate en el primer puesto</p>
    } @else if (datos()!.va_ganando) {
      <p>Va ganando: {{ datos()!.va_ganando!.nombre }} {{ datos()!.va_ganando!.apellido }}</p>
    }

    <table>
      <thead>
        <tr>
          <th>Votante</th>
          <th>Candidato</th>
          <th>Fecha</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        @for (v of datos()!.votos.data; track v.id) {
          <tr>
            <td>{{ v.voter.nombre }} {{ v.voter.apellido }}</td>
            <td>{{ v.candidate.nombre }} {{ v.candidate.apellido }}</td>
            <td>{{ v.voted_at | date: 'medium' }}</td>
            <td>
              <button (click)="verDetalle(v.id)">Ver detalle</button>
            </td>
          </tr>
        }
      </tbody>
    </table>

    <div>
      <button [disabled]="pagina() <= 1" (click)="irAPagina(-1)">Anterior</button>
      <span> Pagina {{ datos()!.votos.current_page }} de {{ datos()!.votos.last_page }} </span>
      <button [disabled]="pagina() >= datos()!.votos.last_page" (click)="irAPagina(1)">Siguiente</button>
    </div>

    @if (detalle(); as d) {
      <div class="modal-overlay" (click)="cerrarDetalle()">
        <div class="modal-content" (click)="$event.stopPropagation()">
          <div class="modal-header">
            <h3>Detalle del voto</h3>
            <button class="modal-close" (click)="cerrarDetalle()" aria-label="Cerrar">&times;</button>
          </div>

          <div class="modal-body">
            <div class="detalle-fila"><span>Documento</span><strong>{{ d.voter.documento }}</strong></div>
            <div class="detalle-fila"><span>Tipo</span><strong>{{ d.voter.tipo }}</strong></div>
            <div class="detalle-fila"><span>Nombre</span><strong>{{ d.voter.nombre }} {{ d.voter.apellido }}</strong></div>
            <div class="detalle-fila"><span>Fecha de nacimiento</span><strong>{{ formatearFecha(d.voter.dob) }}</strong></div>
            <div class="detalle-fila"><span>Direccion</span><strong>{{ d.voter.direccion }}</strong></div>
            <div class="detalle-fila"><span>Telefono</span><strong>{{ d.voter.telefono }}</strong></div>
            <div class="detalle-fila"><span>Sexo</span><strong>{{ d.voter.sexo }}</strong></div>
            <div class="detalle-fila"><span>Voto a</span><strong>{{ d.candidate.nombre }} {{ d.candidate.apellido }}</strong></div>
            <div class="detalle-fila"><span>Fecha del voto</span><strong>{{ d.voted_at | date: 'medium' }}</strong></div>
          </div>

          <button (click)="cerrarDetalle()">Cerrar</button>
        </div>
      </div>
    }
  }
</div>
