// Frontend/src/pages/AgregarVotante.tsx
import { useState } from 'react';
import type { FormEvent } from 'react';
import api from '../api/client';

const soloNumeros = /^[0-9]+$/;

function calcularEdad(fechaNacimiento: string): number {
  const hoy = new Date();
  const nacimiento = new Date(fechaNacimiento);
  let edad = hoy.getFullYear() - nacimiento.getFullYear();
  const mes = hoy.getMonth() - nacimiento.getMonth();
  if (mes < 0 || (mes === 0 && hoy.getDate() < nacimiento.getDate())) {
    edad--;
  }
  return edad;
}

function AgregarVotante() {
  const [documento, setDocumento] = useState('');
  const [tipo, setTipo] = useState<'votante' | 'candidato'>('votante');
  const [nombre, setNombre] = useState('');
  const [apellido, setApellido] = useState('');
  const [dob, setDob] = useState('');
  const [direccion, setDireccion] = useState('');
  const [telefono, setTelefono] = useState('');
  const [sexo, setSexo] = useState<'M' | 'F' | 'Otro'>('M');
  const [mensaje, setMensaje] = useState<{ tipo: 'success' | 'error'; texto: string } | null>(null);
  const [enviando, setEnviando] = useState(false);

  const camposVacios = !documento || !nombre || !apellido || !dob || !direccion || !telefono;

  const handleSubmit = async (e: FormEvent) => {
    e.preventDefault();
    setMensaje(null);

    if (camposVacios) {
      setMensaje({ tipo: 'error', texto: 'Todos los campos son obligatorios.' });
      return;
    }

    if (!soloNumeros.test(documento)) {
      setMensaje({ tipo: 'error', texto: 'El documento solo puede contener numeros.' });
      return;
    }

    if (!soloNumeros.test(telefono)) {
      setMensaje({ tipo: 'error', texto: 'El telefono solo puede contener numeros.' });
      return;
    }

    if (calcularEdad(dob) < 18) {
      setMensaje({ tipo: 'error', texto: 'El votante debe ser mayor de 18 anos.' });
      return;
    }

    setEnviando(true);
    try {
      await api.post('/votantes', {
        documento,
        tipo,
        nombre,
        apellido,
        dob,
        direccion,
        telefono,
        sexo,
      });
      setMensaje({ tipo: 'success', texto: 'Votante agregado correctamente.' });
      setDocumento('');
      setNombre('');
      setApellido('');
      setDob('');
      setDireccion('');
      setTelefono('');
      setTipo('votante');
      setSexo('M');
    } catch (error: any) {
      const texto = error.response?.data?.message ?? 'No se pudo agregar el votante.';
      setMensaje({ tipo: 'error', texto });
    } finally {
      setEnviando(false);
    }
  };

  return (
    <div>
      <h2>Agregar nuevo votante</h2>
      <form onSubmit={handleSubmit}>
        <label htmlFor="documento">Documento</label>
        <input id="documento" value={documento} onChange={(e) => setDocumento(e.target.value)} />

        <fieldset>
          <legend>Tipo</legend>
          <label>
            <input
              type="radio"
              name="tipo"
              value="votante"
              checked={tipo === 'votante'}
              onChange={() => setTipo('votante')}
            />
            Votante
          </label>
          <label>
            <input
              type="radio"
              name="tipo"
              value="candidato"
              checked={tipo === 'candidato'}
              onChange={() => setTipo('candidato')}
            />
            Candidato
          </label>
        </fieldset>

        <label htmlFor="nombre">Nombre</label>
        <input id="nombre" value={nombre} onChange={(e) => setNombre(e.target.value)} />

        <label htmlFor="apellido">Apellido</label>
        <input id="apellido" value={apellido} onChange={(e) => setApellido(e.target.value)} />

        <label htmlFor="dob">Fecha de nacimiento</label>
        <input id="dob" type="date" value={dob} onChange={(e) => setDob(e.target.value)} />

        <label htmlFor="direccion">Direccion</label>
        <input id="direccion" value={direccion} onChange={(e) => setDireccion(e.target.value)} />

        <label htmlFor="telefono">Telefono</label>
        <input id="telefono" value={telefono} onChange={(e) => setTelefono(e.target.value)} />

        <label htmlFor="sexo">Sexo</label>
        <select id="sexo" value={sexo} onChange={(e) => setSexo(e.target.value as 'M' | 'F' | 'Otro')}>
          <option value="M">M</option>
          <option value="F">F</option>
          <option value="Otro">Otro</option>
        </select>

        <button type="submit" disabled={enviando}>
          {enviando ? 'Guardando...' : 'Agregar'}
        </button>
      </form>

      {mensaje && (
        <p className={mensaje.tipo === 'success' ? 'mensaje-exito' : 'mensaje-error'}>
          {mensaje.texto}
        </p>
      )}
    </div>
  );
}

export default AgregarVotante;

// frontend-angular/src/app/pages/admin/agregar-votante/agregar-votante.component.ts
import { Component, inject, signal } from '@angular/core';
import { ReactiveFormsModule, FormBuilder, Validators, AbstractControl, ValidationErrors } from '@angular/forms';
import { VotantesService } from '../../../services/votantes.service';

function mayorDeEdadValidator(control: AbstractControl): ValidationErrors | null {
  const dob = control.value;
  if (!dob) return null;

  const hoy = new Date();
  const nacimiento = new Date(dob);
  let edad = hoy.getFullYear() - nacimiento.getFullYear();
  const mes = hoy.getMonth() - nacimiento.getMonth();
  if (mes < 0 || (mes === 0 && hoy.getDate() < nacimiento.getDate())) {
    edad--;
  }

  return edad >= 18 ? null : { menorDeEdad: true };
}

type Mensaje = { tipo: 'success' | 'error'; texto: string } | null;

@Component({
  selector: 'app-agregar-votante',
  standalone: true,
  imports: [ReactiveFormsModule],
  templateUrl: './agregar-votante.component.html',
  styleUrl: './agregar-votante.component.css',
})
export class AgregarVotanteComponent {
  private fb = inject(FormBuilder);
  private votantesService = inject(VotantesService);

  enviando = signal(false);
  mensaje = signal<Mensaje>(null);

  form = this.fb.nonNullable.group({
    documento: ['', [Validators.required, Validators.pattern(/^[0-9]+$/)]],
    tipo: ['votante' as 'votante' | 'candidato', Validators.required],
    nombre: ['', Validators.required],
    apellido: ['', Validators.required],
    dob: ['', [Validators.required, mayorDeEdadValidator]],
    direccion: ['', Validators.required],
    telefono: ['', [Validators.required, Validators.pattern(/^[0-9]+$/)]],
    sexo: ['M' as 'M' | 'F' | 'Otro', Validators.required],
  });

  agregar(): void {
    this.mensaje.set(null);

    if (this.form.invalid) {
      this.form.markAllAsTouched();
      return;
    }

    this.enviando.set(true);
    this.votantesService.agregar(this.form.getRawValue()).subscribe({
      next: () => {
        this.mensaje.set({ tipo: 'success', texto: 'Votante agregado correctamente.' });
        this.form.reset({ tipo: 'votante', sexo: 'M' });
        this.enviando.set(false);
      },
      error: (err) => {
        const texto = err.error?.message ?? 'No se pudo agregar el votante.';
        this.mensaje.set({ tipo: 'error', texto });
        this.enviando.set(false);
      },
    });
  }
}
<div>
  <h2>Agregar nuevo votante</h2>
  <form [formGroup]="form" (ngSubmit)="agregar()">
    <label for="documento">Documento</label>
    <input id="documento" formControlName="documento" />
    @if (form.controls.documento.touched && form.controls.documento.invalid) {
      <p class="mensaje-error">El documento es obligatorio y solo puede contener numeros.</p>
    }

    <fieldset>
      <legend>Tipo</legend>
      <label>
        <input type="radio" formControlName="tipo" value="votante" />
        Votante
      </label>
      <label>
        <input type="radio" formControlName="tipo" value="candidato" />
        Candidato
      </label>
    </fieldset>

    <label for="nombre">Nombre</label>
    <input id="nombre" formControlName="nombre" />
    @if (form.controls.nombre.touched && form.controls.nombre.invalid) {
      <p class="mensaje-error">El nombre es obligatorio.</p>
    }

    <label for="apellido">Apellido</label>
    <input id="apellido" formControlName="apellido" />
    @if (form.controls.apellido.touched && form.controls.apellido.invalid) {
      <p class="mensaje-error">El apellido es obligatorio.</p>
    }

    <label for="dob">Fecha de nacimiento</label>
    <input id="dob" type="date" formControlName="dob" />
    @if (form.controls.dob.touched && form.controls.dob.errors?.['required']) {
      <p class="mensaje-error">La fecha de nacimiento es obligatoria.</p>
    }
    @if (form.controls.dob.touched && form.controls.dob.errors?.['menorDeEdad']) {
      <p class="mensaje-error">El votante debe ser mayor de 18 anos.</p>
    }

    <label for="direccion">Direccion</label>
    <input id="direccion" formControlName="direccion" />
    @if (form.controls.direccion.touched && form.controls.direccion.invalid) {
      <p class="mensaje-error">La direccion es obligatoria.</p>
    }

    <label for="telefono">Telefono</label>
    <input id="telefono" formControlName="telefono" />
    @if (form.controls.telefono.touched && form.controls.telefono.invalid) {
      <p class="mensaje-error">El telefono es obligatorio y solo puede contener numeros.</p>
    }

    <label for="sexo">Sexo</label>
    <select id="sexo" formControlName="sexo">
      <option value="M">M</option>
      <option value="F">F</option>
      <option value="Otro">Otro</option>
    </select>

    <button type="submit" [disabled]="enviando()">
      {{ enviando() ? 'Guardando...' : 'Agregar' }}
    </button>
  </form>

  @if (mensaje()) {
    <p [class]="mensaje()!.tipo === 'success' ? 'mensaje-exito' : 'mensaje-error'">
      {{ mensaje()!.texto }}
    </p>
  }
</div>
